name = "HugoTeX"
license = "MIT"
licenselink = "https://github.com/hugotex-dev/HugoTeX/blob/main/LICENSE"
description = "LaTeX style hugo theme"
homepage = "https://github.com/hugotex-dev/HugoTeX"
demosite = "https://hugotex.pages.dev/"
tags = ["dark", "light", "blog", "minimal", "simple", "LaTeX"]
features = ["minimal", "simple", "responsive", "syntax highlight", "LaTeX"]
min_version = "0.158.0"

[author]
  name = "hugotex-dev"
  homepage = "https://github.com/hugotex-dev"
